<!DOCTYPE html>
<html>
<head>
	<title>My Personal Portfolio - Md Jubayer Islam (jubayer)</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
	<header>
		<h1>Md Jubayer Islam</h1>
		<h2>Nickname: jubayer</h2>
		<h3>Bangladeshi | Studying Software Engineering at the University of Technology Malaysia</h3>
	</header>
	<main>
		<section>
			<h2>About Me</h2>
			<p>I am a software engineering student with a passion for creating innovative solutions. I love learning about new technologies and applying them to real-world problems. In my free time, I enjoy coding, reading, and playing video games.</p>
		</section>
		<section>
			<h2>Education</h2>
			<ul>
				<li>Bachelor of Software Engineering, University of Technology Malaysia (2019 - present)</li>
				<li>Higher Secondary School Certificate (HSC), Dhaka College, Bangladesh (2017 - 2019)</li>
				<li>Secondary School Certificate (SSC), Govt. Laboratory High School, Dhaka, Bangladesh (2012 - 2017)</li>
			</ul>
		</section>
		<section>
			<h2>Skills</h2>
			<ul>
				<li>Programming languages: Java, Python, C++</li>
				<li>Web development: HTML, CSS, JavaScript, React</li>
				<li>Database management: MySQL, MongoDB</li>
				<li>Tools: Git, Eclipse, IntelliJ, Visual Studio Code</li>
			</ul>
		</section>
		<section>
			<h2>Experience</h2>
			<ul>
				<li>Intern, XYZ Company, Kuala Lumpur, Malaysia (June 2021 - August 2021)</li>
				<li>Volunteer, ABC Organization, Dhaka, Bangladesh (2017 - 2019)</li>
			</ul>
		</section>
		<section>
			<h2>Contact Me</h2>
			<p>Email: jubayer.islam@example.com</p>
			<p>LinkedIn: linkedin.com/in/jubayerislam</p>
			<p>Github: github.com/jubayerislam</p>
		</section>
	</main>
</body>
<style>
	body {
		background-image: url("your-image-url.jpg");
		background-size: cover;
		background-position: center;
	}
</style>
</html>

